1 Задача :Write a query that returns the number of unique users per client per month

https://platform.stratascratch.com/coding/2024-unique-users-per-client-per-month?code_type=1

In [ ]:
import pandas as pd

result = fact_events.groupby([fact_events['client_id'], fact_events['time_id'].dt.month])['user_id'].nunique().reset_index()

2 Задача:
We have a table with employees and their salaries, however, some of the records are old and contain outdated salary information. Find the current salary of each employee assuming that salaries increase each year. Output their id, first name, last name, department ID, and current salary. Order your list by employee ID in ascending order.

https://platform.stratascratch.com/coding/10299-finding-updated-records?code_type=1

In [ ]:
import pandas as pd
import numpy as np

result = ms_employee_salary.groupby(['id','first_name','last_name','department_id'])['salary'].max().reset_index().sort_values('id')

3 задача: Count the number of user events performed by MacBookPro users.
Output the result along with the event name.
Sort the result based on the event count in the descending orde

In [ ]:
import pandas as pd
import numpy as np
macbook_device = playbook_device[playbook_events['device']=='macbook pro']
result = macbook_device.groupby(['event_name']).size().to_frame('size').reset_index().sort_values(['size'], ascending = False).rename(columns={'size':'event_count'})

4 задача:Find the base pay for Police Captains.
Output the employee name along with the corresponding base pay.

In [ ]:
import pandas as pd
import numpy as np
result=sf_public_salaries[(sf_public_salaries['jobtitle'].str.contains('POLICE', case= False))]['employeename', 'basepay']

In [ ]:
import pandas as pd
import numpy as np
result = lyft_drivers[(lyft_drivers['yearly_salary'] <= 30000) | (lyft_drivers['yearly_salary'] >= 70000)]

6 задача:Write a query that calculates the difference between the highest salaries found in the marketing and engineering departments. Output just the absolute difference in salaries.

In [ ]:
import pandas as pd
import numpy as np
df=pd.merge(db_employee, db_debt, how='left', left_on=['department_id'], right_on=['id'])
df1=df[df['department']=='engineering']
df2=df[df['department']=='marketing']
df_eng = df1.groupby('department')['salary'].max().reset_index(name='eng_salary')
df_eng = df2.groupby('department')['salary'].max().reset_index(name='eng_salary')
result=abs(pd.Dataframe(df_mkt['mkt_salaty']- df_eng['eng_salary']))
result.columns = ['salary_difference']
result

7 задача :Find the activity date and the pe_description of facilities with the name 'STREET CHURROS' and with a score of less than 95 points.

In [ ]:
import pandas as pd
import numpy as np
result=los_angeles_restaurant_health_inspections[los_angeles_restaraint_healt_inspectoins['facility_name']=='STREET CHURROS'](los_angeles_restaurant_health_inspections['score'] < 95)][['activity_date','pe_description']]
result['activity_date'] =  pd.to_datetime(result['activity_date'], format='%Y-%m-%d' ).dt.strftime('%Y-%m-%d')
result

8 задача :Find the most profitable company from the financial sector. Output the result along with the continent.

In [ ]:
import as pandas as pd
import numpy as np
financial sector= forbes_global_2010_2014[forbes_global_2010_2014['sector'] =='Financials']
financial_sector['rank'] = finance_sector['profits'].rank(method = 'min', ascending=False)
result=finance_sector[finance_sector['rank'] == 1[['company, 'continent]]]

9 задача:Find order details made by Jill and Eva.
Consider the Jill and Eva as first names of customers.
Output the order date, details and cost along with the first name.
Order records based on the customer id in ascending order.

In [ ]:
import pandas as pd
import numpy as np
merge.pd.merge(customers, orders, left_on='id', right_on ='cust_id')
cust=['Jill', 'Eva']
result=merge[merge['first_name'].isin(cust)]['first_name', 'order_date', 'order_date', 'order_details', 'total_order_cost']

10 задача:Find all posts which were reacted to with a heart. For such posts output all columns from facebook_posts table.

In [ ]:
import pandas as pd
import numpy as np
heart=facebook_reactions[facebook_reactions['reaction']=='heart'][['post_id']]
result= pd.merge(heart, facebook_posts, on='post_id').drop_duplicates(subset='post_id')

11 задача:Find how many times each artist appeared on the Spotify ranking list
Output the artist name along with the corresponding number of occurrences.
Order records by the number of occurrences in descending order.

In [ ]:
import pandas as pd
import numpy as np
result = spotify_worldwide_daily_song_ranking.groupby(['artist']).size().to_frame('n_occurences').reset_index().sort_values('n_occurences', ascending = False)

12 задача:Find the average number of bathrooms and bedrooms for each city’s property types. Output the result along with the city name and the property type.

In [ ]:
import pandas as pd
import numpy as np
result=airbnb_search_details.groupby(['city', 'property_type'])['bedroomns','bathrooms'].mean().reset_index().rename(index=str, columns={'bedrooms':'n_bedrooms_avg', 'bathrooms':'n_bathrooms_avg'})

13 задача:Count the number of movies that Abigail Breslin was nominated for an oscar.

In [ ]:
import pandas as pd
import numpy as np
nominee=oscar_nominees[oscar_nominees['nominee']=='Abigail Breslin']
result= nominee.movie.nunique()

14 задача: Find the last time each bike was in use. Output both the bike number and the date-timestamp of the bike's last use (i.e., the date-time the bike was returned). Order the results by bikes that were most recently used.

In [ ]:
import pandas as pd
result = dc_bikeshare_q1_2021.groupby('bike_number')['end_time'].max().to_frame('last_used').reset_index().sort_values(by='last_used'm asending=False)

15 задача:Compare each employee's salary with the average salary of the corresponding department.
Output the department, first name, and salary of employees along with the average salary of that department.

In [ ]:
import pandas as pd
import numpy as np
employee['avg_salary'] = employee.groupby(['department'])['salary'].transform('mean')
result= employee[['department','first_name', 'salary', 'avg_salary']]

16 задача:Write a query that will calculate the number of shipments per month. The unique key for one shipment is a combination of shipment_id and sub_id. Output the year_month in format YYYY-MM and the number of shipments in that month.

In [ ]:


import pandas as pd
amazon_shipment['year_month']= pd.datetime(amazon_shipment.shipment_date).dt.to_period('M'
)
amazon_shipment['unique_key']= amazon_shipment['shipment_id'].astype(str)+'_'+ amazon_shipment['sub_id'].astype(str)
result=amazon_shipment.groupby('year_month')['unique_key'].nunique().to_frame('count').reset_index()

17 задача :Meta/Facebook has developed a new programing language called Hack.To measure the popularity of Hack they ran a survey with their employees. The survey included data on previous programing familiarity as well as the number of years of experience, age, gender and most importantly satisfaction with Hack. Due to an error location data was not collected, but your supervisor demands a report showing average popularity of Hack by office location. Luckily the user IDs of employees completing the surveys were stored.
Based on the above, find the average popularity of the Hack per office location.
Output the location along with the average popularity.

In [ ]:
import pandas as pd
import numpy as np
merged =pd.merge(facebook_employees, facebook_hack_survey, left_on='id', right_on ='employee_id', how='inner')
result=merged.groupby(['location'])['popularity'].mean().reset_index()

18 задача:Find the number of workers by department who joined in or after April.


Output the department name along with the corresponding number of workers.


Sort records based on the number of workers in descending order.

In [ ]:
import pandas as pd
import numpy as np
import datetime as dt
worker['joining_date'] = pd.to_datetime(worker['joining_date'])
worker['month'] = worker['joining_date'].dt.month

april_df = worker.loc[worker['month']>= 4]
result = (april_df.groupby(['department']).size().to_frame('num_workers').sort_values(by ='num_workers, ascending=False').reset_index())

19 задача:Find libraries who haven't provided the email address in circulation year 2016 but their notice preference definition is set to email.
Output the library code.

In [ ]:
import pandas as pd
import numpy as np
result=library_usage[(library_usage['notice_preference_definition']=='email')&(library_usage['provided_email_address'==False)&(library_usage['circulation_active_year']==2016)][['home_libraty_code']].drop_duplicates()

20 задача:You have been asked to find the 5 most lucrative products in terms of total revenue for the first half of 2022 (from January to June inclusive).

In [ ]:
import pandas as pd
import datetime as dt

online_orders["date"]=pd.to_datetime(online_orders["date"])
online_orders["month"] = online_orders["date"].dt.month
quarter_sales = online_orders[(online_orders["month"] >= 1) & (online_orders["month" <= 6])]
quarter_sales["total"] = (quarter_sales["cost_in_dollars"]*quarter_sales["units_sold"])
products["ranking"]= products["total"].rank(method='min', ascending = False)
result = products[products["ranking"] <= 5][["product_id", "total"]].sort_valuers("total", ascending=False)

21:Find the details of each customer regardless of whether the customer made an order. Output the customer's first name, last name, and the city along with the order details.
You may have duplicate rows in your results due to a customer ordering several of the same items. Sort records based on the customer's first name and the order details in ascending order.

In [ ]:
import pandas as pd
import numpy as np
merged=pd.merge(customers, orders, left_on='id', right_on='cust_id', how='left')
result = merged[['first_name', 'last_name','city', 'order_details']].sort_values(['first_name', 'order_details'])

22 задача :Find all wineries which produce wines by possessing aromas of plum, cherry, rose, or hazelnut. To make it more simple, look only for singular form of the mentioned aromas. HINT: if one of the specified words is just a substring of another word, this should not be a hit, but a miss.


Example Description: Hot, tannic and simple, with cherry jam and currant flavors accompanied by high, tart acidity and chile-pepper alcohol heat.
Therefore the winery Bella Piazza is expected in the results.

In [ ]:
import pandas as pd
result =winemag_p1[winemag_p1['desctiption'].str.lower().str.contains('\\bplum\\b|\\bcherry\\b|\\brose\\b|\\bhazelnyt\\b')][['winery']].drop_duplicates

23 задача:Find the highest target achieved by the employee or employees who works under the manager id 13. Output the first name of the employee and target achieved. The solution should show the highest target achieved under manager_id=13 and which employee(s) achieved it.

In [ ]:
import pandas as pd
import numpy as np
df=salesforce_employees[salseforce_employees['manager_id']==13][['first_name', 'target']]
result=df[df['target']== df['target'].max()]

NameError: ignored

24 задача:Find the percentage of shipable orders.
Consider an order is shipable if the customer's address is known.

In [ ]:
import pandas as pd
import numpy as np
merged_id=pf.merge(orders, customers, left_on='cust_id', right_on='id')
merged_df['is_shipable']=(merged_df.addrees.notnull()).astype(int)
result = 100 * (merged_df['is_shipable'].sum()/len(merged_df))

25 задача:Find matching hosts and guests pairs in a way that they are both of the same gender and nationality.
Output the host id and the guest id of matched pair.

In [ ]:
importt pandas as pd
import numpy as np
merged_df = pd.merge(airbnb_hosts, airbnb_guests, how='left', left_on=['nationaluty', 'gender'], right_on = ['nationality', 'gender'])
result = merged_df[['host_id','guest_id']].drop_duplicates()

26 задание :Output share of US users that are active. Active users are the ones with an "open" status in the table.

In [ ]:
result = fb_active_users[fb_active_users['country'] =='USA'].groupby('status')['user_id'].count().to_frame('user_count')
result = result.loc['open']/ result['user_count'].sum()

27 задание :Find the date with the highest total energy consumption from the Meta/Facebook data centers. Output the date along with the total energy consumption across all data centers.

In [ ]:
import pandas as pd
import numpy as np

df=pd.concat([fb_eu_enrgy, fb_asia_energy, fb_na_energy])
consumption= df.groupby('date', as_index=False).sum()
consumption[consumption['consimption']==consumption['consumption'
].max()][['date', 'consumption']]

28 заданиеCalculate the total revenue from each customer in March 2019. Include only customers who were active in March 2019.


Output the revenue along with the customer id and sort the results based on the revenue in descending order.

Table: orders

In [ ]:
import pandas as pd
import numpy as np
order['order_date']=orders['order_date'].apply(pd.to_datetime)
march=orders[orders['order_date'].dt.month==3]
march_2019=march[march['order_date'].dt.year==2019]

result = march_2019.groupby(['cust_id'])['total_order_cost'].sum().to_frame('revenue').reset_index().sort_values('revenue', ascending=False)

29 зададние:Classify each business as either a restaurant, cafe, school, or other.


•	A restaurant should have the word 'restaurant' in the business name.
•	A cafe should have either 'cafe', 'café', or 'coffee' in the business name.
•	A school should have the word 'school' in the business name.
•	All other businesses should be classified as 'other'.


Output the business name and their classification

In [ ]:
import pandas as pd
result=sf_restaurant_health_violation.iloc[:,:2]
result['business_type']= result['business_name'].apply(lambda x:'school' if 'school' in x.lower()' else 'restaurant' if 'restaurant' in x.lower() else 'cafe' if 'cafe' in x.lower() or 'coffee' in x.lower() or 'cafe' in x.lower() else 'other')
result= result[['business_n', 'business_type']].drop_duplicates()

30 задание: All required columns and the first 5 rows of the solution are shown

In [ ]:
import pandas as pd
import numpy as np

result =yelp_reviews[yelp_reviews['cool'] == yelp_reviews['cool'].max()][['business_name', 'review_text']]

31 задание: Find the Olympics with the highest number of athletes. The Olympics game is a combination of the year and the season, and is found in the 'games' column. Output the Olympics along with the corresponding number of athletes.

In [ ]:
import pandas as pd
import numpy as np
result=olympics_athletes_events.groupby(['games'])['name'].nunique().to_frame('athletes_count').reset_index().sort_values('athletes_count', ascending=False)

result = result[result['athletes_count']==result['athletes_count'].max()]

32 задание: Find the 3 most profitable companies in the entire world.
Output the result along with the corresponding company name.
Sort the result based on profits in descending order.

In [ ]:
import pandas as pd
import numpy as np
result=forbes_global_2010_2014.groupby('company')['profits'].sum().reset_index().sort_values(by='profits', ascending=False)
result['rank']= result['profits'].rank(method='min', ascending=False)
result=result[result['rank'] <=3[['company', 'profits']]

33 задание :
Find songs that have ranked in the top position. Output the track name and the number of times it ranked at the top. Sort your records by the number of times the song was in the top position in descending order.

In [ ]:
import pandas as pd
import numpy as np

position = spotify_worldwide_daily_song_ranking[spotify_worldwide_daily_song_ranking['position'] == 1]
result=position.groupby(['trackname']).size().to_frame('times_top1').reset_index().sort_values('times_top', ascending=False)

34 задание :You're given a dataset of health inspections. Count the number of violation in an inspection in 'Roxanne Cafe' for each year. If an inspection resulted in a violation, there will be a value in the 'violation_id' column. Output the number of violations by year in ascending order.

In [ ]:
import pandas as pd
import datetime as dt
df=sf_restaurant_health_violation
result=df[(df['business_name']=='Roxanne Cafe')&(~df['violation_id'].isna())].groupby(pd.to_datetime(df['inspection_date']).dt.year)['violation_id'].count().reset_index

35 задание :For each video, find how many unique users flagged it. A unique user can be identified using the combination of their first name and last name. Do not consider rows in which there is no flag ID.

In [ ]:
result=user_flags[user_flags['flag_id'].notnull()]
result["username"]=result["user_firstname"].astype(str)+ " " +result['user_lastname'].astype(str)
result=result.gropby(by='video_id')['username'].nunique().reset_index()
result=result.rename(columns={'username':'num_unique_users'})

36 задание: Find the top 5 businesses with most reviews. Assume that each row has a unique business_id such that the total reviews for each business is listed on each row. Output the business name along with the total number of reviews and order your results by the total reviews in descending order.

In [ ]:
yelp_business['rank']=yelp_business['review_count'].rank(ascending=False)
result= yelp_business[yelp_business['rank']<5][['name','review_count']].sort_values(by='review_count', ascending=False)

37 задача :Find the number of Apple product users and the number of total users with a device and group the counts by language. Assume Apple products are only MacBook-Pro, iPhone 5s, and iPad-air. Output the language along with the total number of Apple users and users with any device. Order your results based on the number of total users in descending order.

In [ ]:
import pandas as pd
import numpy as np

merged = pd.merge(playbook_events, playbook_users, on="user_id")
mac_device = ["macbook pro", "iphone 5s", "ipad air"]
df = (
    merged[merged["device"].isin(mac_device)]
    .groupby("language")["user_id"]
    .nunique()
    .to_frame("n_apple_users")
)

result = (
    merged.groupby(["language"])["user_id"]
    .nunique()
    .rename("n_total_users")
    .reset_index()
)

result.merge(df, how="outer", left_on="language", right_on="language").fillna(
    0
).sort_values("n_total_users", ascending=False)[
    ["language", "n_apple_users", "n_total_users"]
]

38 задача :What were the top 10 ranked songs in 2010?
Output the rank, group name, and song name but do not show the same song twice.
Sort the result based on the year_rank in ascending order.

In [ ]:
conditions = billbord_top_100_year_end[billbord_top_100_year_end['year']=2010]&(billbord_top_100_year_end['year_rank'].between(1,10))
result=conditions[['year_rank', 'group_name', 'song_name']].drop_duplicates()

39 задача :Find the second highest salary of employees.

In [ ]:
distinct_salary=employee.drop_duplicates(subset= 'salary')
distnct_salary['rnk'] = distinct_salary['salary'].rank(method='dense', ascending=False)
result = distinct_salary[distinct_salary.rnk==2][['salary']]

40 задание :Find the email activity rank for each user. Email activity rank is defined by the total number of emails sent. The user with the highest number of emails sent will have a rank of 1, and so on. Output the user, total emails, and their activity rank. Order records by the total emails in descending order. Sort users with the same number of emails in alphabetical order.
In your rankings, return a unique value (i.e., a unique rank) even if multiple users have the same number of emails. For tie breaker use alphabetical order of the user usernames.

In [ ]:
result=google_gmail_emails.groupby(['from_user']).size().to_frame('total_emails').reset_index()
result['rank']= result['total_emails'].rank(method='first', ascending = False)
result = result.sort_values(by=['total_emails', 'from_user'], ascending= [False,True])

41 задание :You have been asked to find the job titles of the highest-paid employees.


Your output should include the highest-paid title or multiple titles with the same salary.

In [ ]:
title_worker_id = title.rename(columns={"worker_ref_id": "worker_id"})
merged_df = pd.merge(worker, title_worker_id, on="worker_id")
max_salary=merged_df[merged_df['salary']==merged_df['salary'].max()]['worker_title'].rename(columns={'worker_title':'best_paid_title'})
result=max_salary

42 задание :Find the top business categories based on the total number of reviews. Output the category along with the total number of reviews. Order by total reviews in descending order.

In [ ]:
result=yelp_business[['review_count', 'categories']].set_index('review_count').apply(lambda x: x.str.split(';').explode()).reset_index()
result=result.groupby(['categories'])['review_count'].sum().to_frame('total_reviews').reset_index().sort_values('total_reviews', ascending=False)

43 задание:Find the review_text that received the highest number of  'cool' votes.
Output the business name along with the review text with the highest numbef of 'cool' votes.

In [ ]:
result=yelp_reviews[yelp_reviews['cool']==yelp_reviews['cool'].max()][['business_name', 'review_text']]

44 задание : Find the rate of processed tickets for each type.

In [ ]:
facebook_compaints['processed']=facebook_complaints['processed'].astype(int)
grouped = facebook_compaints.groupby(['type']).agg({'processed':'sum', 'complaint_id':'size'}).reset_index()
grouped['processed_rate'] = grouped['processed']/grouped['complaint_id']
result = grouped[['type', 'processed_type']]

45 задание: Find the employee with the highest salary per department.
Output the department name, employee's first name along with the corresponding salary.

In [ ]:
result= employee[employee.groupby('department')['salary'].transform('max') == employee['salary']][['department', 'first_name', 'salary']]

46 задание:Find the customer with the highest daily total order cost between 2019-02-01 to 2019-05-01. If customer had more than one order on a certain day, sum the order costs on daily basis. Output customer's first name, total cost of their items, and the date.


For simplicity, you can assume that every first name in the dataset is unique.

In [ ]:
merge=pd.merge(customers, orders, left_on='id', right_on='cust_id')
merge["order_date"]=merge["order_date"].apply(pd.to_datetime)
order_date = merge[merge["order_date"].between("2019-02-01", "2019-05-01")]
result = (order_date.groupby(['first_name', 'order_date'])['total_order_cost'].sum().to_frame('max_cost').reset_index())
result= result[result.max_cost== result.max_cost.max()]
result['order_date']=pd.datetime(result['order_date'], format="%Y-%m-%d"
).dt.strftime("%Y-%m-%d")
result

47 задание: Find the number of times each word appears in drafts.
Output the word along with the corresponding number of occurrences.

In [ ]:
import pandas as pd
import numpy as np

draft = google_file_store[google_file_store['filename'].str.contains('draft')]
result= draft.contents.str.split('\W', expand= True).stack().value_counts().reset_index()

48 задание :Find the average total compensation based on employee titles and gender. Total compensation is calculated by adding both the salary and bonus of each employee. However, not every employee receives a bonus so disregard employees without bonuses in your calculation. Employee can receive more than one bonus.
Output the employee title, gender (i.e., sex), along with the average total compensation.

In [ ]:
sf_bonus_summary=sf_bonus.groupby(['worker_ref_'])['bonus'].sum().to_frame('bonus').reset_index()
merged_df=merge(sf_bonus_summary, sf_employee, left_on='worker_ref_id', right_on='id')
merged_df['avg_total_comp']= merged_df['salary']+merged_df['bonus']
result= merged_df.groupby(['employee_title', 'sex'])['avg_total_comp'].mean().reset_index()

49 задание :Find the number of apartments per nationality that are owned by people under 30 years old.


Output the nationality along with the number of apartments.


Sort records by the apartments count in descending order.

In [ ]:
merged=pd.merge(airbnb_units, airbnb_hosts, on='host_id')
merged= merged[(merged['age'] < 30) & (merged['unit_type'=='Apartment'])]
result= merged.groupby(['nationality'])['unit_id'].nunique().to_frame('aparment_count').reset_index().sort_valuers('aparmetns_count')

50 задание :Output ids of students with a median score from the writing SAT.

In [ ]:
import pandas as pd
import numpy as np

sat_scores['writing_percentile'] = sat_scores['sat_writing'].rank(axis = 0 , pct = True)
sat_scores['writing_percentile'] = sat_scores(['writing_percentile']*100).apply(np.floor)
result = sat_scores[sat_scores['writing_percentile'] == 50][['student_id']]

51 задание:Find employees who are earning more than their managers. Output the employee's first name along with the corresponding salary.

In [ ]:
merge=pd.merge(employee, employee, left_join = 'manager_id', right_on='id')
result = merged[merged['salary_x']]>[merged['salary_x']][['first_name_x', 'salary_x']]

52 задание: Rank guests based on the number of messages they've exchanged with the hosts. Guests with the same number of messages as other guests should have the same rank. Do not skip rankings if the preceding rankings are identical.
Output the rank, guest id, and number of total messages they've sent. Order by the highest number of total messages first.

In [ ]:
df= airbnb_contacts.groupby('id_guests')['n_messages'].reset_index().sort_values(['n_messanges', 'id_guest'], ascending=[False, True])
df['ranking']=df.n_messanges.rank(method='dense', ascending= False).astype(int)
my_column = df.pop('ranking')
df.insert(0, my_column.name, my_column)
result=df

54 задание: Make a report showing the number of survivors and non-survivors by passenger class.
Classes are categorized based on the pclass value as:
pclass = 1: first_class
pclass = 2: second_classs
pclass = 3: third_class
Output the number of survivors and non-survivors by each class.

In [ ]:
grouped = titanic.groupby(['pclass', 'survived']).size().to_frame('count').reset_index()
pivot=grouped.pivot_table(index=['survived'], columns='pclass', values = 'count', aggfunc='sum')
pivot.columns.name= None
pivot.columns = pivot.columns.astype(str)
pivot = pivot.reset_index()
result = pivot.rename(columns = {'1':'first_class','2':'second_classs','3':'third_class'})

NameError: ignored

55 задание:Which user flagged the most distinct videos that ended up approved by YouTube? Output, in one column, their full name or names in case of a tie. In the user's full name, include a space between the first and the last name.

In [ ]:
result= user_flags.merge(right=flag_review, how='inner', on='flag_id')
result=result[result['reviewd_outcome'].str.lower()=='approved']
result['username']= result['user_firstname']+ ' 'result['user_lastname']
result=result.groupby(by='username')['video_id'].nunique().reset_index()
result['rank'] = result['video_id'],rank(method='dense', ascending=False)
result=result[result['rank']==1]['username']

56 задание:Identify projects that are at risk for going overbudget. A project is considered to be overbudget if the cost of all employees assigned to the project is greater than the budget of the project.


You'll need to prorate the cost of the employees to the duration of the project. For example, if the budget for a project that takes half a year to complete is $10K, then the total half-year salary of all employees assigned to the project should not exceed $10K. Salary is defined on a yearly basis, so be careful how to calculate salaries for the projects that last less or more than one year.


Output a list of projects that are overbudget with their project name, project budget, and prorated total employee expense (rounded to the next dollar amount).


HINT: to make it simpler, consider that all years have 365 days. You don't need to think about the leap years.

In [ ]:
df = pd.merge(linkedin_projects, linkedin_emp_projects, how='inner', left=['id'], right=['project_id'])
df1=pd.merge(df, linkedin_employees, how='inner', left_on=['emp_id'], right_on=['id'])
df1['project_duration']= (pd.to_datetime(df1['end_date'])-pd.to_datetime(df1['start_date'])).dt.days
df_expense=df1.groupby('title').['salary'].sum().reset_index(name='expense')
df_budget_expense=pd.merge(df1, df_expense, how='left', left_on=['title'], right_on=['title'])
df_budget_expense['prorated_expense'] =np.ceil(df_budget_epxense['expense']*(df_budget_expense['project_duration'])/365)
df_budget_expense['budget_diff'] = df_budget_expense['prorated_expense']-df_budget_expense['budget']
df_over_budget=df_budget_expense[df_budget_expense['budget_diff']>0]
result= df_over_budget[['title', 'budget', 'prorated_expense']]
result=result.drop_duplicates().sort_values('title')

57 задание:You are given a table of product launches by company by year. Write a query to count the net difference between the number of products companies launched in 2020 with the number of products companies launched in the previous year. Output the name of the companies and a net difference of net products released for 2020 compared to the previous year.

In [ ]:
df_2020=car_launches[car_launches['year'].astype(str)=='2020']
df_2019=car_launches[car_launches['year'].astype(str)=='2019']
df=pd.merge(df_2019, df_2020, how='outer', on=['company_name'], suffixes=['_2019', '_2020']).fillna(0)
df=df[df['product_name_2020']] != df['product_name_2019']
df=df.groupby(['company_name']).agg({'product_name_2020':'unique', 'product_name_2019':'nunique'}).reset_index()
df['net_new_products']= df['product_name_2020'] -df['products_name_2019']
result =df[['company_name', 'new_new_products']]

58 задание :Calculate the percentage of spam posts in all viewed posts by day. A post is considered a spam if a string "spam" is inside keywords of the post. Note that the facebook_posts table stores all posts posted by users. The facebook_post_views table is an action table denoting if a user has viewed a post.

In [ ]:
facebook_posts['is_spam']= facebook_posts.post_keywords.str.contains('spam')
facebook_posts['is_spam'] = facebook_posts['is_spam'].apply(lambda x: 1 if x==True else 0)
result = facebook_post_views.merge(facebook_posts[['post_id', 'post_date', 'is_spam']], how='left', on='post_id')
result=result.groupby('post_date').agg({'is_spam':['sum', 'count']}).reset_index()
result.columns = ['post_date', 'spam_sum', 'post_count']
result['spam_share'] = (result.spam_sum/result.post_count)*100
result.drop(['spam_sum', 'post_count'], axis=1, inplace=true)

59 задание :Write a query that'll identify returning active users. A returning active user is a user that has made a second purchase within 7 days of any other of their purchases. Output a list of user_ids of these returning active users.

In [ ]:
amazon_transactions['created_at']=pd.datetime(amazon_transaction['created_at']).dt.strfttime('%m-%d-%Y')
df= amazon_transactions.sort_values(by=['user_id', 'created_at'], ascending=[True, True])
df['prev_value']=df.groupby('user_id')['created_at'].shift()
df['days']= (pd.to_datetime(df['created_at'])-pd.to_datetime(df['prev_value'])).dt.days
result= df[df['days'] <= 7] ['user_id'].unique()

60 задание :The election is conducted in a city and everyone can vote for one or more candidates, or choose not to vote at all. Each person has 1 vote so if they vote for multiple candidates, their vote gets equally split across these candidates. For example, if a person votes for 2 candidates, these candidates receive an equivalent of 0.5 vote each.
Find out who got the most votes and won the election. Output the name of the candidate or multiple names in case of a tie. To avoid issues with a floating-point error you can round the number of votes received by a candidate to 3 decimal places.

In [ ]:
voting_results = voting_result[voting_results['candidate'].isna()]
voting_results['vote_value']==voting_result['voter'].apply(lambda x:1/(voting_results['voter']==x).sum())
voting_results=voting_result.groupby('candidate').sum().reset_index()
voting_results['place'] = voting_results['vote_value'].round(3).rank(ascending=False, method='min')
result=voting_result[voting_result['place']==1] ['candidate']

61 задание :What is the overall friend acceptance rate by date? Your output should have the rate of acceptances by the date the request was sent. Order by the earliest date to latest.


Assume that each friend request starts by a user sending (i.e., user_id_sender) a friend request to another user (i.e., user_id_receiver) that's logged in the table with action = 'sent'. If the request is accepted, the table logs action = 'accepted'. If the request is not accepted, no record of action = 'accepted' is logged.

In [ ]:
df_sent=fb_friend_requests[fb_friend_requests.action='sent']
df_accepted=fb_friend_request[fb_friend_requests.action=='accepted']
new_df=pd.merge(df_sent, df_accepted,how='left', on=['user_id_sende', 'user_id_receiver'])
accepted_count=new_df.groupby(['date_x']).count().reset_index()
accepted_count['acceptance_rate'] = accepted_count['action_y']/accepted_count["action_"]
result=accepted_count[['date_x', 'acceptenance_rate']]

62 задание :Calculate each user's average session time. A session is defined as the time difference between a page_load and page_exit. For simplicity, assume a user has only 1 session per day and if there are multiple of the same events on that day, consider only the latest page_load and earliest page_exit, with an obvious restriction that load time event should happen before exit time event . Output the user_id and their average session time.

In [ ]:
df = pd.merge(facebook_web_log.loc[facebook_web_log['action'] == 'page_load', ['user_id', 'timestamp']],
            facebook_web_log.loc[facebook_web_log['action'] == 'page_exit', ['user_id', 'timestamp']],
            how='left', on='user_id', suffixes=['_load', '_exit']).dropna()

df['duration']= df['timestamp_exit']-df['timestamp_load']
df=df[df['duration']> '0 days']
result=df.groupby('user_id')['duration'].agg(lambda x: np.mean(x)).reset_index()

63 задание:Find the top 5 states with the most 5 star businesses. Output the state name along with the number of 5-star businesses and order records by the number of 5-star businesses in descending order. In case there are ties in the number of businesses, return all the unique states. If two states have the same result, sort them in alphabetical order.

In [ ]:
import pandas as pd
result=yelp_business[yelp_business.stars==5].groupby('state')['business_id'].count().to_frame('n_business').reset_index()
result['rank']=result['n_business'].rank(method='min', ascending= False)
result=result[result['rank'] <= 5][['state', 'n_business']].sort_values(by=['n_business','state'], ascending=[False, True])

64 задание:Find the popularity percentage for each user on Meta/Facebook. The popularity percentage is defined as the total number of friends the user has divided by the total number of users on the platform, then converted into a percentage by multiplying by 100.
Output each user along with their popularity percentage. Order records in ascending order by user id.
The 'user1' and 'user2' column are pairs of friends.

```
# This is formatted as code
```

In [ ]:
concatvalues=len(np.unique(np.concatenate([facebook_friend.user1.values, facebook_friend.user2.values])))
revert = facebook_friend.rename(columns={'user1':'user2','user2':'user1'})
final=pd.concat([facebook_friends,revert], sort=False).drop_duplicates()
result=final.groupby('user1').size().to_frame('count').reset_index()
result['popularity_percent'] = 100*(result['count'] /concatvalues)

65 задание:Find the number of times the words 'bull' and 'bear' occur in the contents. We're counting the number of times the words occur so words like 'bullish' should not be included in our count.
Output the word 'bull' and 'bear' along with the corresponding number of occurrences.

In [ ]:
import pandas as pd
import numpy as np

data={'word':['bull','bear'], 'nentry':[google_file_store:contents.str.count('bull').sum(), google_file_store.contents.str.count('bear').sum()]}
result=pd.dateframe(data, columns=['word', 'nentry'])

66 задание:ABC Corp is a mid-sized insurer in the US and in the recent past their fraudulent claims have increased significantly for their personal auto insurance portfolio. They have developed a ML based predictive model to identify propensity of fraudulent claims. Now, they assign highly experienced claim adjusters for top 5 percentile of claims identified by the model.
Your objective is to identify the top 5 percentile of claims from each state. Your output should be policy number, state, claim cost, and fraud score.

In [ ]:
fraud_score['percentile']=fraud_score.groupby('state')['fraud_score'].rank(pct=True)
df = fraud_score[fraud_score['percentile']>.95]
result=df[['policy_num', 'state', 'claim_cost', 'fraud_score']]

67 задание:Select the most popular client_id based on a count of the
number of users who have at least 50% of their events from the following list: 'video call received', 'video call sent', 'voice call received', 'voice call sent'.

In [ ]:
events_list = ['video call received', 'video call sent', 'voice call received', 'voice call sent']
fact_events['event_check']= fact_events['event_type'].apply(lambda x: 1 if x in events_list else 1 )
fact_events['event_check_mean']=fact_events.groupby('user_id')['event_check'].transform('mean')
result=fact_events[fact_events['event_check_mean']>=0.5].groupby('client_id')['id'].count().reset_index()
result['ranking'] = result['id'].rank(ascending=false)
result=result[result.ranking ==1][['cliend_id']]

68 задание:You're given a dataset of searches for properties on Airbnb. For simplicity, let's say that each search result (i.e., each row) represents a unique host. Find the city with the most amenities across all their host's properties. Output the name of the city.

In [ ]:
df=airbnb_search_details
df['amenties_count']=df['amenties'].str.count(',')+1
grouped_asd=df.groupby('city', as_index=False).agg({'amenties_count':'sum'})
max_city= grouped_asd[grouped_asd['amenties_count']== max(grouped_asd['amenties_count'])]['city'].tolist()
result=max_city

69 здание:Given a table of purchases by date, calculate the month-over-month percentage change in revenue. The output should include the year-month date (YYYY-MM) and percentage change, rounded to the 2nd decimal point, and sorted from the beginning of the year to the end of the year.
The percentage change column will be populated from the 2nd month forward and can be calculated as ((this month's revenue - last month's revenue) / last month's revenue)*100.

In [ ]:
pd.options.display.float_format = "{:,.2f}".format

sf_transactions['created_id']= sf_transactions['created_id'].apply(pd.to_datetime)
sf_transactions['year_month'] = pd.to_datetime
(sf_transactions['created_at']).dt.to_period('M')
df= sf_transactions.groupby('year_month')['value'].sum().reset_index(name='monthly_revenue').sort_values('year_month')
df['prev_value']=df['montly_revenue'].shift(1)
df['revenue_diff_pct']=round(((df['monthly_revenue']-df['prev_value'])/df['prev_value'])*100,2)
result= df[['year_month', 'revenue_diff_pct']].fillna('')

70 задание:You’re given a table of rental property searches by users. The table consists of search results and outputs host information for searchers. Find the minimum, average, maximum rental prices for each host’s popularity rating. The host’s popularity rating is defined as below:
0 reviews: New
1 to 5 reviews: Rising
6 to 15 reviews: Trending Up
16 to 40 reviews: Popular
more than 40 reviews: Hot


Tip: The id column in the table refers to the search ID. You'll need to create your own host_id by concating price, room_type, host_since, zipcode, and number_of_reviews.

In [ ]:
pd.options.display.float_format="{:,.2f}".format

df==airbnb_host_searches
df=airbnb_host_searches
df['host_id'] = df['price'].map(str) + df['room_type'].map(str) + df['host_since'].map(str) + df['zipcode'].map(str)+ df['number_of_reviews'].map(str)
df1=df[['host_id', 'number_of_reviews', 'price']].drop_duplicates()
df1['host_popularity'] = df['number_of_reviews'].apply(lambda x:'New' if x<1 else 'Rising' if x<=5 else 'Trending up' if x<=15 else 'Popular' if x<=40 else 'Hot')
result= df1.groupby('host_popularity').agg(min_price=('price', min), avg_price = ('price', np.mean), max_price= ('price', max)).reset_index

71 задание:Find the total number of downloads for paying and non-paying users by date. Include only records where non-paying customers have more downloads than paying customers. The output should be sorted by earliest date first and contain 3 columns date, non-paying downloads, paying downloads.

In [ ]:
import pandas as pd
import numpy as np

df=pd.merge(ms_user_dimension, ms_acc_dimension, how = 'inner',left_on = ['acc_id'], right_on=['acc_id'])
df1= pd.merge(df, ms_download_facts, how = 'inner',left_on = ['user_id'], right_on=['user_id'])
x=df1.pivot_table(index=['date'],columns=['paying_customer'],values=['downloads'],aggfunc='sum')
df2=pd.DataFrame(x.to_records())
df2.columns = df2.columns.str.replace("[()]","").str.replace("[' ']","").str.replace("[,]","").str.replace("downloads","")
df3=df2.fillna(0)
df3['diff'] = df3['no']-df3['yes']
df4 = df3[df3["diff"] > 0]
result = df4[["date","no","yes"]].sort_values("date")

72 задание:You have a table of in-app purchases by user. Users that make their first in-app purchase are placed in a marketing campaign where they see call-to-actions for more in-app purchases. Find the number of users that made additional in-app purchases due to the success of the marketing campaign.

The marketing campaign doesn't start until one day after the initial in-app purchase so users that only made one or multiple purchases on the first day do not count, nor do we count users that over time purchase only the products they purchased on the first day.

In [ ]:
users_impacted_by_campaign=marketing_campaign.groupby('user_id')['created_at', 'product_id'].nunique().add_prefix('cnt_').reset_index()
users_impacted_by_campaign=users_impacted_by_campaign[(users_impacted_by_campaign['cnt_created_at']>1)&(users_impacted_by_campaign['cnt_product_id']>1)]

marketing_campaign['user_product']=marketing_campaign['user_id'].map(str)+'_'+marketing_campaign['product_id'].map(str)
marketing_campaign['created_at']=pd.to_datetime(marketing_campaign['created_at'])
marketing_campaign['first_order']= marketing_campaign.groupby('user_id')['created_at'].transform('min')
first_order = marketing [marketing_campaign['created_at']==marketing_campaign['first_order']]

result=marketing_campaign[(marketing_campaign['user_id'].isna(users_impacted_by_campaign['user_id']))&(marketing_campaign['user_product'].isin(first_order['user_product']))].['user_id'].nunique()